version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    restart: always
    networks:
       myapp:
    volumes:
      - mydata:/var/lib/mysql
    env_file:
      - .env
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: always
    networks:
      myapp:
    volumes:
      - vol-app:/var/www/html
    depends_on:
      - wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    restart: always
    networks:
      myapp:
    volumes:
      - vol-app:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
networks:
  myapp:
volumes:
  vol-app:
    driver: local
    driver_opts:
      type: none
      device: /home/fbouibao/data/wordpress
      o: bind
  mydata:
    driver: local
    driver_opts:
      type: none
      device: /home/fbouibao/data/mariadb
      o: bind